#!/usr/bin/env python
# -*- coding: utf-8 -*-
import win32com,os
from win32com.client import Dispatch, constants
import psutil

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

copyrows =3000
startrows =20
endcol =30

wjx_user="13058659320"   #问卷星帐号
wjx_pw="Lilyhcn123"      #问卷星密码
wj_id="41236383"         #问卷的ID
wjx_download = "C:\\Users\\lily\\Downloads"      #chrome下载文件后的默认目录
dir_path = os.getcwd() + "\\xlsm" #文件

    
def SheetCopys(path,path2):
    xlApp = win32com.client.DispatchEx("Excel.Application")
    xlApp.Visible = True
    xlApp.DisplayAlerts = 0
    #第一个文件
    xlBook = xlApp.Workbooks.Open(path,False)
    sht = xlBook.Worksheets('sheet1')  #找到要操作的sheet
    sht.Activate
    sht.Select()
    range_list=sht.Range(sht.Cells(1, 1), sht.Cells(copyrows, endcol)).Value
    xlBook.Close(True)
    xlApp.quit()
    
     #第二个文件       
    xlBook = xlApp.Workbooks.Open(path2,False)
    sht = xlBook.Worksheets('1.原始表')  #找到要操作的sheet
    sht.Activate
    sht.Select()
    sht.Range(sht.Cells(1+startrows, 1), sht.Cells(copyrows+startrows, endcol)).Value = range_list
    xlBook.save
    #执行宏
    sht = xlBook.Worksheets('1.原始表')  #找到要操作的sheet
    sht.Activate
    sht.Select()
    sht.Application.Run(' 执行1上传_2下截_3上传') #宏
    xlBook.save
    xlBook.Close(True)
    xlApp.quit()    

def GetWjx():
    brower= webdriver.Chrome()
    brower.get("https://www.wjx.cn/login.aspx")
    brower.set_window_size(898, 585)
    time.sleep(1)
    brower.find_element(By.ID, "UserName").send_keys(wjx_user)
    brower.find_element(By.ID, "Password").send_keys(wjx_pw)
    brower.find_element(By.ID, "LoginButton").click()
    time.sleep(1)
    brower.get("https://www.wjx.cn/wjx/activitystat/viewstatsummary.aspx?activity=" + wj_id + "&reportid=-1&dw=1&dt=0")
    time.sleep(3)
    brower.quit()
    
def Delallfiles(dirs):
    for file in os.listdir(dirs):
        temp =  dirs + "\\" +file
        os.remove(temp)



#清空文件夹
Delallfiles(wjx_download)

#从问卷星网站上下载数据        
GetWjx()

# 获取文件名
for file in os.listdir(wjx_download):
    path = wjx_download + "\\" +file
for file in os.listdir(dir_path):
    path2 = dir_path + "\\" +file
    
#操作excel文件内容过来，其中最后是上传文件
SheetCopys(path,path2)






print("执行完成")
